@token=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiODRjN2MzZjAtZjk3Zi00ZmJlLTkwNmItYjE2YzQ5NTBhNmViIiwidGVuYW50cyI6WyJjM2VjYzIyMy00Y2RiLTRjNzQtODliZS01MjdjZWI0MWI5N2MiXSwidHlwZSI6ImFjY2VzcyIsImlzcyI6IktPU1ZJIiwic3ViIjoiODRjN2MzZjAtZjk3Zi00ZmJlLTkwNmItYjE2YzQ5NTBhNmViIiwiZXhwIjoxNzQ0Nzg1NjY3LCJuYmYiOjE3NDQ3ODIwNjcsImlhdCI6MTc0NDc4MjA2N30.fJuXlVaDNhtyIwMrE3xQrDidahQoHyPkVxTrfc68xtMoSm8kKC1sWVZ3y9-sNmP-LFmOv83JspoK1a8PQ5-oXA
@refresh_token=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiODRjN2MzZjAtZjk3Zi00ZmJlLTkwNmItYjE2YzQ5NTBhNmViIiwidHlwZSI6InJlZnJlc2giLCJpc3MiOiJLT1NWSSIsInN1YiI6Ijg0YzdjM2YwLWY5N2YtNGZiZS05MDZiLWIxNmM0OTUwYTZlYiIsImV4cCI6MTc0NDc4OTI2NywibmJmIjoxNzQ0NzgyMDY3LCJpYXQiOjE3NDQ3ODIwNjd9.McuicJNXBYVEUocTS9hhu3Dy_cV1y5mIBa7QTcA68nXqP718OyiT-gVI7v8INN6IjnnsjbTqTxKEBMLI4vc5Tw
@tenant=c3ecc223-4cdb-4c74-89be-527ceb41b97c

### Register
POST http://localhost:8080/api/v1/register
content-type: application/json

{
    "name": "test 1",
    "email": "test1@test.com",
    "password": "test1"
}

### Login
POST http://localhost:8080/api/v1/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

### Register tenant
POST http://localhost:8080/api/v1/tenant
Authorization: {{token}}
content-type: application/json

{
    "name": "test 1"
}

### Refresh
POST http://localhost:8080/api/v1/refresh
content-type: application/json
Authorization: {{token}}

{
    "token": "{{token}}",
    "refresh_token": "{{refresh_token}}"
}

### Get Tenant
GET http://localhost:8080/api/v1/tenants
Authorization: {{token}}

### Run Admin Migrations
POST http://localhost:8080/api/v1/migrations/admin
Authorization: {{token}}

### Run Tenant Migrations
POST http://localhost:8080/api/v1/migrations/tenant
Authorization: {{token}}
X-Tenant-Id: {{tenant}}

### Productos
### Get Productos
GET http://localhost:8080/api/v1/productos?fields=data{id,precio}&page=1&size=3&filter={"AND":[{"id":{"gt":1}}]}&sort=[{"precio":{"dir":"desc"}}]
Authorization: {{token}}
X-Tenant-Id: {{tenant}}

### Create Productos
POST http://localhost:8080/api/v1/productos
Authorization: {{token}}
X-Tenant-Id: {{tenant}}
content-type: application/json

{
    "nombre": "Jugo de Natura 4",
    "precio": 40000
}

### Get Carrito Compra
GET http://localhost:8080/api/v1/carrito-compra
Authorization: {{token}}
X-Tenant-Id: {{tenant}}

### Create Carrito Compra
POST http://localhost:8080/api/v1/carrito-compra
Authorization: {{token}}
X-Tenant-Id: {{tenant}}
content-type: application/json

{
    "producto_id": 1,
    "cliente_id": 1,
    "cantidad": 2,
    "id": 1
}
